#!/bin/bash

base=$(dirname $0)
. $base/settings.ini
. $base/functions.ini

OBJ=$(abbr_object $1)
shift

case $1 in
    list)
        # no other args for now
        get_list "$OBJ" | straw_extract_list | straw_summarize "$OBJ"
        ;;
    fetch)
        # 2nd arg is uuid
        fetch "$OBJ" "$2"
        ;;
    fetchstraw|fetchstrawberry)
        # uuid
        fetch "$OBJ" "$2" | straw_extract_one
        ;;
    get|summarize)
        # uuid
        fetch "$OBJ" "$2" | straw_extract_one | straw_summarize "$OBJ"
        ;;
    search)
        # search string (title)
        titlesearch "$OBJ" "$2"  | straw_extract_list | straw_summarize "$OBJ"
        ;;
    uploadfiles)
        # uuid files
        UUID="$2"
        shift;shift
        processfiles "$OBJ" "$@"
        new=$(fetch "$OBJ" "$UUID" | straw_extract_one | addfiles | php_json_encode)
        patchobj "$OBJ" "$UUID" "$new"
        ;;
    deploy|new)
        # title desc tags grp  files
        TITLE=$(echo "$2" | php_json_encode)
        DESC=$(echo "$3" | php_json_encode)
        TAGS='\u0022'${4//,/\\u0022,\\u0022}'\u0022'
        GRP="$5"
        shift;shift;shift;shift;shift
        UUID=$(uuidgen)
        processfiles "$OBJ" "$@"
        newobj "$OBJ"
        ;;
    *)
        echo not imp yet
        ;;
esac
